server:
  port: 9601
spring:
  profiles:
    active: dev
  application:
    name: smile-auth-resource
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
